// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecantoImperial.Api.Data;

#nullable disable

namespace RecantoImperial.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251210173143_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("RecantoImperial.Api.Models.Ave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Anilha")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<byte>("AuriculaDespigPercent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuriculaPoints")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BarbelaDesigualdadePercent")
                        .HasColumnType("TEXT");

                    b.Property<int>("BarbelaPoints")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Barbuda")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Canelas")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Caracteristicas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorBico")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("CristaPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CristaTombamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Idade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Linhagem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("OlhosVermelhos")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PescocoPelado")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PlumagemBarrada")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PlumagemCarijo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PlumagemFrisada")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlumagemPattern")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("PontosTotais")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegistroObservacoes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistroResultado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sexo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusDescricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Anilha")
                        .IsUnique();

                    b.ToTable("Aves");
                });

            modelBuilder.Entity("RecantoImperial.Api.Models.Backup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Caminho")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Backups");
                });

            modelBuilder.Entity("RecantoImperial.Api.Models.Cruzamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cruzamentos");
                });

            modelBuilder.Entity("RecantoImperial.Api.Models.CruzamentoAves", b =>
                {
                    b.Property<int>("CruzamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AveId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("CruzamentoId", "AveId");

                    b.HasIndex("AveId");

                    b.ToTable("CruzamentoAves");
                });

            modelBuilder.Entity("RecantoImperial.Api.Models.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AveId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AveId");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("RecantoImperial.Api.Models.Relatorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataGeracao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Relatorios");
                });

            modelBuilder.Entity("RecantoImperial.Api.Models.CruzamentoAves", b =>
                {
                    b.HasOne("RecantoImperial.Api.Models.Ave", "Ave")
                        .WithMany("CruzamentoAves")
                        .HasForeignKey("AveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecantoImperial.Api.Models.Cruzamento", "Cruzamento")
                        .WithMany("CruzamentoAves")
                        .HasForeignKey("CruzamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ave");

                    b.Navigation("Cruzamento");
                });

            modelBuilder.Entity("RecantoImperial.Api.Models.Evento", b =>
                {
                    b.HasOne("RecantoImperial.Api.Models.Ave", "Ave")
                        .WithMany("Eventos")
                        .HasForeignKey("AveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ave");
                });

            modelBuilder.Entity("RecantoImperial.Api.Models.Ave", b =>
                {
                    b.Navigation("CruzamentoAves");

                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("RecantoImperial.Api.Models.Cruzamento", b =>
                {
                    b.Navigation("CruzamentoAves");
                });
#pragma warning restore 612, 618
        }
    }
}
